### ISSUE TITLE
permissions i gues

### ISSUE THREAD

**Issue by MatessakCZE** [wargamer/SignShop#104]
hello i have problems my friends doesnt have op and they cant buy any item how i can repair it

**Comment by weaves7** [comment]
This is usually caused by a plugin interfering with SignShop or the built in vanilla spawn protection. Try changing spawn-protection=16 to spawn-protection=0 in server.properties. If you have Essentials installed try disabling all of the Essentials signs including -color by commenting them out.  Otherwise you can use your permission plugin's verbose logging to see what permissions are being checked when they try to use a sign. i.e. /LuckPerms verbose on or /pex toggle debug.
