### ISSUE TITLE
[Enhancement] Buy Items With Exp Levels

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [wargamer/SignShop#108]
iBuyXP, iSellXP, Trade, iBuy, iSell.
While all very useful, none of these allow this feature.

Would be awesome if this could be added! Thanks!

**Comment by PiggiesGoSqueal** [comment]
Could be: [iBuyItemXP] or something.

**Comment by weaves7** [comment]
There are already infinite shops that use XP:
iXPBuy: takePlayerXP{raw},givePlayerItems,playerIsOp
iXPSell: givePlayerXP{raw},takePlayerItems,playerIsOp

You could also copy the takePlayerXP and givePlayerXP operations to other shops in the config or create your own shops by using combinations of these and other operations. There is more info in the [SSQuickRefence.pdf](https://github.com/wargamer/SignShop/blob/master/src/main/resources/SSQuickReference.pdf) in your SignShop folder. However there is no option to give xp to or take xp from the shop owner since they may be offline so these will only work with server shops.
