### ISSUE TITLE
[Suggestion] Expand the trade feature

### ISSUE THREAD

**Issue by kfirar** [wargamer/SignShop#117]
My suggestions are:

- Make only the signs that use a soft currency require Vault, this way you can download the plugin as a standalone just for the trade signs.
- Make item versions of [DeviceOn], [DeviceOff] and [Toggle]. There already exists a [DeviceItem] so something like that for the other device related signs would be appreciated.
- Make a two way version of [Trade].

**Comment by weaves7** [comment]
Hi,
I was just looking at this again and realized I should have mentioned that you can already make custom signs like the ones that you have suggested for item based DeviceOn, DeviceOff, and Toggle signs.
In the config you will see that [DeviceItem] is listed as `DeviceItem: takePlayerItems, giveShopItems, setRedstoneOnTemp` and [DeviceOn] is listed as `DeviceOn: takePlayerMoney, giveOwnerMoney, setRedstoneOn` You can take the desired operations from each sign and create a new sign. For example [DeviceOnItem] (you may have to come up with a shorter name to fit on the sign) you could add to the signs: list `DeviceOnItem: takePlayerItems, giveShopItems, setRedstoneOn` then under the various messages you could add DeviceOnItem and the appropriate corresponding message. Then do the same for DeviceOff and Toggle. Not sure what you mean by two way version of [Trade]. If you just want to trade the other way you could add another trade sign to the same chests but linked the other way. I don't think it would be possible to add that function to the same trade sign since it could break existing shops on servers that have used the plugin for years. I think the Vault requirement should stay since most servers that use SignShop would be using a soft currency and those that don't could just not use the soft currency signs and Vault will not have any effect on server performance. Vault is also needed for some permission based transactions and command signs.
