### ISSUE TITLE
Transactions failed to add money when selling too quick

### ISSUE THREAD

**Issue by PeeeKayy** [wargamer/SignShop#124]
I was trying to setup a place to trade diamonds for money so i made a [isell] sign, linked with a chest.
![image](https://user-images.githubusercontent.com/94774312/145516305-8e071713-f889-4abd-a612-ffb8b615e2dd.png)

But if i held down right click or just sell them a little quick in general. The chat messenges will pop up accordingly but the money in bal seems missing.
![image](https://user-images.githubusercontent.com/94774312/145516577-ac44064e-7e07-47d5-ada0-5689840162ac.png)
As shown in the img above. I've clicked the sign 4 times, and 4 diamonds is gone, but the bal only got 3 out of 4 transactions 

This is my start up logs
[Logs.txt](https://github.com/wargamer/SignShop/files/7690087/Logs.txt)

**Comment by weaves7** [comment]
It turns out that this is a problem with EconomyPlus. EconomyPlus fails on about 40% of quick player deposit transactions but it always returns to SignShop that the transaction was a success. I tested SignShop for this issue with several other vault economies including EssentialsX, CMI, TheosisEconomy, and EconomyX with zero failures.
