### ISSUE TITLE
Add SignShop to pom.xml

### ISSUE THREAD

**Issue by Gashmob** [wargamer/SignShop#136]
I made an economy plugin for a server and i tried to link it to SignShop. When i tried to compile my ide tell me that he cannot found the classes (`org.wargamer2010.signshop.events.SSMoneyTransactionEvent`).

So i tried to do `mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=SignShop-3.6.2.jar` to add it to my maven depedencies. Maven tell that all is ok. But when i do `mvn clean compile` with my ide, he tell me again that he cannot found the classes.

**Comment by weaves7** [comment]
I am not sure what you are trying to do, but SignShop hooks to economies with Vault, not directly. If you are trying to listen to the event perhaps you have a typo somewhere in an import statement or when you ran one of those commands. Not much I can do to help without seeing the actual errors. For faster help, join the Discord https://discord.gg/4wnyysf

**Comment by weaves7** [comment]
It was figured out in Discord that the `mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=<path-to-file>` command installed the artifact in their local repository under `org.makershaven` and their pom.xml was looking under `org.wargamer2010` The fix is to either change the pom.xml to match or use  `mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>` to correctly specify the id.
