### ISSUE TITLE
Toggle signs not updating redstone if levers are on walls

### ISSUE THREAD

**Issue by RoyCurtis** [wargamer/SignShop#19]
If a `[Toggle]` sign is wired to levers which are attached to a block vertically, the toggle signs will toggle the state of the levers visually but the redstone signal itself will not update. This means that doors, pistons, etc. will not toggle.

Video explanation; https://www.youtube.com/watch?v=pXpvsQOF2yw
Examples of non-working and working setups, respectively: http://i.imgur.com/5dtVRUw.png http://i.imgur.com/cjvpMHO.png

## Details

* CraftBukkit version git-Spigot-b73910a-aa92a45 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
* Server plugins: http://i.imgur.com/QSLUAD0.png
* SignShop version: 2.9.1Dev (build 68)
* Vault version: 1.5.2-b33
* Tested with region, permissions, signshop flags and LWC flags checked

## Reproduction

1. Place a lever on the side of a block
2. Place a door on top of that block
3. Toggle lever to confirm it opens and closes
4. Place a sign nearby with `[Toggle]` as the first line
5. Punch the lever with a piece of redstone
6. Punch the `[Toggle]` sign with a piece of redstone
7. Confirm in chat that SignShop has created a new toggle sign
8. Right-click the sign with an empty hand a few times
9. Observe that the lever changes, but the door does not

**Comment by wargamer** [comment]
I'm sad to say this is a known issue and nothing Signshop has any influence over. We're tried really hard to fix this half a year ago but we weren't able to. 

In code, we tell the lever to switch on or off and it's then Bukkit/Minecraft's task to run the redstone logic. Again, Signshop does not have any direct say in how that's handled. There are ways to manually trigger redstone, but that gets complicated really, really quickly because of all the garbage method names and such. 

So Dev and I decided not to fix it. Primarily because it doesn't seem to be our place to do so. Bukkit should.

I really appreciate your elaborate bug report though. If only every bug report would be in that format...

**Comment by RoyCurtis** [comment]
Understood; I was afraid it would be an upstream problem. I will see if I can bring more attention to this by the Spigot team. Thank you for the explanation!

(And sorry, I did not catch your response whilst posting issue #20)
