### ISSUE TITLE
[critical] SignShopPlayerListener (PlayerInteractEvent) creating dramatic lag on 1.12 (V2.11.2)

### ISSUE THREAD

**Issue by FrozenBeard** [wargamer/SignShop#44]
Using PaperSpigot latest 1139 build. (1.12)
Using SignShop 2.11.2

I just had a server crash after I had 50+ people online, The issue is Signshop.
From Timings report:

http://i.imgur.com/JsXu4MF.png

The signshop event:
Minecraft::Packet - PacketPlayInBlockDig
SignShop::Event: o.w.s.l.SignShopPlayerListener (PlayerInteractEvent)

is causing dramatic lag.

is there any way we can diagnose the issue and get it fixed please?

**Comment by Devinish** [comment]
What is your server hardware? RAM / CPU / Disk speed are the most important.  Usually this is caused by the server not being able to handle the load.  It's not that SignShop is taking too long, it's that the server is chugging, and SignShop just happens to be at the top of the list.

**Comment by FrozenBeard** [comment]
its a dedicated server.
Core™ i5-3570s Benchmark score: 6568 4c / 4t 3.1 GHz+ 
16 GB Ram
1 TB HDD 
100 Mbps Network

I've been running SignShop for a few years now, I only recently updated yesterday, did it have to convert anything? I have a MASSIVE Transaction.log and 4835 signs shops signs made.

**Comment by SeDark** [comment]
Any solution to this?

**Comment by FrozenBeard** [comment]
@SeDark No it was just ignored. :(

**Comment by Devinish** [comment]
PlayerInteractEvent just means that someone has interacted with SignShop, and now SignShop needs to do something to make sure that interaction is valid, which usually involves database lookups and things.  Often times this is SignShop waiting for the account information / transaction to take place in the economy plugin.  This can be because you are using some remote SQL server instead of something on disk, or that the disk is too slow (is it an SSD?).  We have servers with thousands of players using SignShop without these sorts of issues.  I'm not sure your CPU is enough for 50+ people either (see these specs from the wiki [https://minecraft.gamepedia.com/Server/Requirements/Dedicated]).  I just don't think that server is strong enough for that sort of load.  There's nothing more we can tell you to fix this issue other than you probably need better hardware, unfortunately.

**Comment by FrozenBeard** [comment]
dead plugin, recommend better alternatives?
