### ISSUE TITLE
Plugin outdated on Spigot. 

### ISSUE THREAD

**Issue by TheCoolOne123** [wargamer/SignShop#56]
I'd like to know if this plugin is still being maintained. If not I'd like to continue it.

**Comment by TheCoolOne123** [comment]
As seen on #55 #49 #46 #40 and #31.

The plugin is not really being updated anymore as it's used to be. So I'd like to take over the plugin. Because there aren't alot of signshop plugins supporting 1.12+/1.13+ correctly (Due to the major paper/spigot/minecraft changes)

**Comment by dustyhunsaker** [comment]
We would be happy to have someone take over the plugin.  Because we can't just go giving it to someone without the skills and time to work on it, we would want you to make some modifications / updates to some of the current issues before we could completely hand it over.  Got any ideas in mind?

**Comment by DeveloperJose** [comment]
I'm also interested in helping update the plugin a bit. I've noticed that there are a lot of hooks to plugins which are no longer actively supported or were last updated a long time ago. I was wondering what your thoughts on that were. Would it be better to remove them altogether? Should we just include the latest JAR files for them? I'm not sure if that would bring stability problems?

Deadbolt was last updated Jun 23, 2014
WhatIsIt on May 19, 2015
LoreLocks on Jul 14, 2014
Notifications on Jan 17, 2014
SpoutCraft on May 30, 2014

These plugins seem to still be actively updated:
GriefPrevention (https://www.spigotmc.org/resources/griefprevention.1884/)
LWC (https://www.spigotmc.org/resources/lwc-extended.69551/)
Residence (https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-15.11480/)
Dynmap (https://www.spigotmc.org/resources/dynmap.274/)
Towny (https://www.spigotmc.org/resources/towny-advanced.72694/)
Essentials (https://www.spigotmc.org/resources/essentialsx.9089/)
WorldGuard (https://dev.bukkit.org/projects/worldguard)
VaultAPI (https://www.spigotmc.org/resources/vault.34315/)
Skript (https://www.spigotmc.org/resources/categories/skript.25/)

**Comment by dustyhunsaker** [comment]
My thought is that we would just deprecate support for those plugins.  Those hooks are non-essential to most people, I'd guess.  Of course, if those plugins still work, then I'd keep it around.  Just because a plugin hasn't been updated in a while, doesn't necessarily mean it doesn't work.

**Comment by DeveloperJose** [comment]
Hmm that makes sense. It seems the biggest issue is the fact that the plugin uses a lot of deprecated API calls. I believe I can help a little with updating some parts of it. Would it be fine to submit pull requests? Or perhaps you might feel that there are some more important issues that could be addressed?

**Comment by dustyhunsaker** [comment]
I think we would welcome pull requests.  @wargamer Do you still have the project on your machine to test that sort of thing?  I don't at the moment, but I'm sure I could get it setup again.

**Comment by weaves7** [comment]
I have already done a lot of this in my fork. I have a working 1.15.2  version. I would also like to release it on spigot as SignShop v3. However it is not currently compatible with old ss data. I could pr to this repo as well and/or accept pr's. Sorry to hijack this thread but I just wanted to let you guys know so you didn't waste your time doing what I already have.

**Comment by dustyhunsaker** [comment]
I think the best thing to do would be to maintain this repository, keep the same Spigot / dev.bukkit pages, and hand it off to someone who really has the time to maintain them.  This way players can keep going to the same place, etc.  Of course you are free to do as you like, as SignShop is licensed very permissibly.

**Comment by weaves7** [comment]
I understand the license  is very permissive I just think asking for permission is the right thing to do. I would be open to either scenario. I have the time and I am on Spigot daily(staff). I guess it would be up to the current page maintainers to decide if I am worthy, so-to-speak.

**Comment by dustyhunsaker** [comment]
I agree with you.  I also realized I'm signed into my professional github account and not my one for this repo, but I'm one of the maintainers (Devinish).

**Comment by wargamer** [comment]
> 
> 
> I understand the license is very permissive I just think asking for permission is the right thing to do. I would be open to either scenario. I have the time and I am on Spigot daily(staff). I guess it would be up to the current page maintainers to decide if I am worthy, so-to-speak.

I'd be more than happy to add you as a Collaborator to this repository as your fork definitely makes you worthy of continuing work on SignShop :)
Is that something you can work with? If so, I'll get it done today or tomorrow.

**Comment by weaves7** [comment]
That works for me.

**Comment by wargamer** [comment]
Done, you are now a Collaborator for this repo.
I'd appreciate it if you could shoot me a message when you've released a new version of SignShop somewhere :) Not because I want to review your work, I'd simply like to see the response from the community.

**Comment by weaves7** [comment]
Will do, it will be a bit since I would like to reintroduce compatibility with old ss data and do plenty of testing.

**Comment by lieuweberg** [comment]
Haha, over the past few days I've also updated the plugin to work with recent versions. I'm happy I don't have to maintain another big project now though. Also, I'm sure the community will love it! We've been looking for a new plugin for a long time but nothing works how we want to.

**Comment by dustyhunsaker** [comment]
@lieuweberg Can you submit a PR so we can merge those changes in?

**Comment by lieuweberg** [comment]
I'm still trying to fix a few things, most notably the plugin appending Legacy in front of every item name. This code base is completely new for me. You may also want to wait for weaves7's fork to be complete, since mine isn't as great and also won't be. It still uses a lot of deprecated methods and I'm relatively new to Java. About the only thing I did so far is build the spigot 1.15.2 jar and fixing the errors a few deprecated methods and class (notably Lever -> Switch, MaterialData -> BlockData).

**Comment by TheCoolOne123** [comment]
Dammmm, I missed alot here xD. Sorry for the late response :P. Had been busy. Looks like that changed very fast

**Comment by weaves7** [comment]
@wargamer @dustyhunsaker  I am not sure what all Collaborator is supposed to grant me but it seems like it does not allow me to have write access. (I don't see where it even applied anything) Devinish added me to dev.bukkit but I cannot edit the overview, I can only upload files. He also talked with me on Spigot but there I can only edit the page(due to being staff) but I cannot upload files. I am not sure how to proceed. In the mean time I have submitted a pr with my current changes and have more on the way.

**Comment by wargamer** [comment]
@weaves7 Good to hear the Collaborator thing works. I'm sure @dustyhunsaker can help you out with the file upload over at Spigot.
@lieuweberg weaves7's PR has just been merged with master. Your help is still very much welcome though! Feel free to open a PR.

**Comment by dustyhunsaker** [comment]
@wargamer I think he is saying that the collaborator did NOT work.  

@weaves7 Ok, I guess the overview doesn't count as a "page" according to dev.bukkit, I gave you the ability to edit "settings" so now you should be good to go.  The only things left to give are managing members and changing the license.  Since that PR was merged in, I guess at some point We'll have to setup a test area.  I don't even think I have MC installed at the moment, but I had an area setup with all the different signs and things in it to make sure it was all working before a release.  Any chance you want to make something like that?  I'd be happy to upload the jar files onto the spigot page when we get something tested and releasable.

**Comment by weaves7** [comment]
@dustyhunsaker Sounds good. I already have a shared host that I use for testing plugins. As well as testing on my pc as I go. I will give you the IP in a Spigot pm. You can share it with whoever is relavent I just don't want it on a public repo.

**Comment by weaves7** [comment]
@dustyhunsaker @wargamer I have made a simple Discord server where we can chat easier: https://discord.gg/czPJg7a

**Comment by weaves7** [comment]
https://www.spigotmc.org/resources/signshop.10997/
